### ISSUE TITLE
cml up when topology.yaml file present starts a new lab

### ISSUE THREAD

**Issue by usmcfiredog** [CiscoDevNet/virlutils#109]
**Describe the bug**
When I have a folder that contains a topology.yaml file and I issue the command cml up creates a new lab for that yaml file instead of using the existing lab that has already been created.

**To Reproduce**
1. Download yaml file from CML
2. go to where you downloaded it and issue the command cml up
3. now go to cml ls and it will show 2 labs running with the same name but different IDs

**Expected behavior**
cml up with a topology file present should start the lab that is already present on the server

**Comment by xorrkaz** [comment]
What version of cmlutils do you have, and how _exactly_ are you running the command?

**Comment by usmcfiredog** [comment]
running virlutils 1.1.0 and I am just using cml up

**Comment by xorrkaz** [comment]
This should be fixed in the upcoming 1.2.0.  If you want, clone this repo, and checkout the joe-dev branch and test it out.  Note: you will need to run `pip install -U virl2_client` first to update your client library.  Note: that this will only work the way you want if the current lab points to the lab already on CML.  If the current lab is not set, then it will re-upload the lab as a second instance.  If you want to use an existing lab on the CML server, use `cml use` first.

**Comment by usmcfiredog** [comment]
sounds good I currently have virl2-client version 2.1.0rc1. Do you by chance know when the new virlutils will be released?

**Comment by xorrkaz** [comment]
That's the version of virl2-client you need.  I plan to release 1.2.0 next week when CML 2.1 is released.

**Comment by usmcfiredog** [comment]
since I have that installed should I uninstalled the virlutils then? or do I need both virlutils and virl2-client installed?

**Comment by xorrkaz** [comment]
You need them both.  The virlutils suite requires virl2-client.

**Comment by usmcfiredog** [comment]
stupid question on a side note. Where are the tab completion files I would like to figure out a way to add tab completion for different nodes

**Comment by xorrkaz** [comment]
If you mean the bash and zsh command completion, that is learned from the commands themselves.

**Comment by xorrkaz** [comment]
This is believed to have been fixed in virlutils 1.2.0.
